[build]
  command = "npm run build"
  publish = "dist"
  # Disable functions directory scanning
  functions = ""

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_FLAGS = "--force"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200