// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkltwcqerheayysqkwqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrbHR3Y3FlcmhlYXl5c3Frd3F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzAzOTksImV4cCI6MjA2MzYwNjM5OX0.5CLzJxnAV0SZ-s-7t0Ig1giQHWlcMTLkmnGOFLpFzWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);