// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://voejoqmfluaohpyrcbub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvZWpvcW1mbHVhb2hweXJjYnViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2Mjg1MzAsImV4cCI6MjA2MzIwNDUzMH0.VDAFxA7xtx5KsveCn2vm4k6WXYBvZPLcdF_bdPTq62o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);